apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-vda-service"
  labels:
    {{- include "mon-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mon-chart.selectorLabels" . | nindent 4 }}
